version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:80
    networks:
      - CC_Network

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
    env_file:
      - ./backend/.env
    depends_on:
      - redis-server
    networks:
      - CC_Network

  redis-server:
    build:
      context: ./redis
      dockerfile: ./Dockerfile
    networks:
      - CC_Network

networks:
  CC_Network:
