apiVersion: v1
kind: PersistentVolume
metadata:
  name: info-app-persistent-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /data/redis/