apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: note-server
  name: note-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: note-server
  strategy: {}
  template:
    metadata:
      labels:
        app: note-server
    spec:
      containers:
        - image: deliiiled/cc_fp:backend.1.0
          name: note-server
          ports:
            - containerPort: 3001
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: note-secret
                  key: DB_PASSWORD
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: note-config
                  key: PORT
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: note-config
                  key: DB_URL
            - name: URL_EXP
              valueFrom:
                configMapKeyRef:
                  name: note-config
                  key: URL_EXP

status: {}
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: note-server
#   name: note-server-service
# spec:
#   allocateLoadBalancerNodePorts: true
#   externalTrafficPolicy: Cluster
#   internalTrafficPolicy: Cluster
#   ipFamilies:
#     - IPv4
#   ipFamilyPolicy: SingleStack
#   ports:
#     - name: 8095-8095
#       nodePort: 31788
#       port: 8095
#       protocol: TCP
#       targetPort: 8095
#   selector:
#     app: note-server
#   sessionAffinity: None
#   type: LoadBalancer
# status:
#   loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: note-server
  name: note-service
spec:
  ports:
    - name: 3001-3001
      port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: note-server
  type: LoadBalancer
status:
  loadBalancer: {}
